<?php

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('application', ['action' => 'add']) ?>">Add new album</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($albums as $album) :?>
    <tr>
        <td><?= $this->escapeHtml($album->getTitle()); ?></td>
        <td><?= $this->escapeHtml($album->getContent()); ?></td>
        <td>
            <a href="<?= $this->url('application', ['action' => 'edit', 'id' => $album->getId()]) ?>">Edit</a>
            <a href="<?= $this->url('application', ['action' => 'delete', 'id' => $album->getId()]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>